name: Test
on:
  workflow_dispatch:
    inputs:
      test:
        description: Test
        required: false
        default: 'hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "It works!"
